saasapp/config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'health', to: 'pages#health'
  get 'aviation', to: 'pages#aviation'
  get 'technology', to: 'pages#technology'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  get 'careers', to: 'pages#careers'
end

saasapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

saasapp/app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :phone_number, presence: true
  validates :comments, presence: true
end

saasapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

saasapp/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      name = params[:contact][:name]
      email = params[:contact][:email]
      phone = params[:contact][:phone_number]
      body = params[:contact][:comments]
      ContactMailer.contact_email(name, email, phone, body).deliver
      flash[:success] = "Message sent."
      redirect_to new_contact_path
    else
      flash[:danger] = @contact.errors.full_messages.join(", ")
      redirect_to new_contact_path
    end
  end
  
  private
    def contact_params
       params.require(:contact).permit(:name, :email, :phone_number, :comments)
    end
end

saasapp/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
  
  def health
  end
  
  def aviation
  end
  
  def technology
  end
  
  def careers
  end
end

saasapp/app/helpers/application_helper.rb
module ApplicationHelper
end

saasapp/app/views/contacts/new.html.erb
<div class="container expand">
  <div class="row">
    <h3 class="text-center">Contact Us</h3>
    <div class="col-md-4 col-md-offset-4">
      <div class="well">
        <%= form_for @contact do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :phone_number %>
            <%= f.text_field :phone_number, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :comments %>
            <%= f.text_area :comments, class: 'form-control' %>
          </div>
          <%= f.submit 'Submit', class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

saasapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HAVIT Consulting</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-105657593-1"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
      
        gtag('config', 'UA-105657593-1');
      </script>

  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon bar"></span>
            <span class="icon bar"></span>
            <span class="icon bar"></span>
          </button>
          <%= link_to "/", class: "navbar-brand" do %>
            <i class="fa fa-group"></i>
            HAVIT Consulting
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About Us", "/about" %></li>
            <li><div class="dropdown">
              <button class="dropbtn">Services</button>
              <div class="dropdown-content">
                <%= link_to "Health", health_path %>
                <%= link_to "Aviation", aviation_path %>
                <%= link_to "Technology", technology_path %>
              </div>
            <li><%= link_to "Contact Us", new_contact_path %></li>
            </div></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
    </div>
    <%= yield %>
    
    <nav class="navbar navbar-default footer" role="footer">
      <div class='container'>
        <div class="row">
          
          <div class="col-md-4">
            <ul class="navi">
              <li class="text-center"><h4>Social Media</h4></li>
              <li class="text-center">
                <%= link_to "http://www.instagram.com/havitcoaching", class: "text-center" do %>
                  <i class="fa fa-instagram"></i>
                  Instagram
                <% end %></li>
              <li class="text-center">
                <%= link_to "http://www.facebook.com/havitcoaching", class: "text-center" do %>
                  <i class="fa fa-facebook-square"></i>
                  Facebook
                <% end %></li>
              <li class="text-center">
                <%= link_to "https://www.linkedin.com/company/24426811/", class: "text-center" do %>
                  <i class="fa fa-linkedin-square"></i>
                  LinkedIn
                <% end %></li>
            </ul>
          </div>
          
          <div class="col-md-4">
            <ul class="navi">
              <li class="text-center"><h4>HAVIT Divisions</h4></li>
              <li class="text-center"><%= link_to "Health", health_path %></li>
              <li class="text-center"><%= link_to "Aviation", aviation_path %></li>
              <li class="text-center"><%= link_to "Technology", technology_path %></li>
            </ul>
          </div>
          
          <div class="col-md-4">
            <h4 class="text-center text-footer"> </h3>
            <ul class="navi">
              <li class="text-center"><%= link_to "Contact Us", new_contact_path %></li>
              <li class="text-center"><%= link_to "Careers", careers_path %></li>
              <br />
              <br />
              <li class="text-center"><i class="fa fa-copyright"></i> Copyright 2018 HAVIT Consulting</li>
            </ul>
          </div>
          
        </div>
      </div>
    </nav>
  </body>
</html>

saasapp/app/views/pages/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-3 col-xl-2">
      <%= image_tag("img_0014.gif", :alt=> "Norm Walker", class: "img-responsive bio") %>
    </div>
    <div class="col-xs-8 col-sm-8 col-md-9 col-lg-9 col-xl-10">
      <h1>Norm Walker</h1>
      <p class="text-justify">Managing Partner Norm Walker provides expertise in the Aerospace and 
      Defense markets with a long and successful background in the commercial 
      and US government business segments. Specialties and experience include: 
      Sales/Marketing, Business Development, Capture/Capture Management, 
      Proposal Development/Proposal Management, USG and Commercial Pricing, 
      Estimating and Contracts, Program Management, ITAR and Employee Training.</p>
      <p class="text-justify">Mr. Walker provides a truly ‘cradle to grave’ business accumen. Mr. Walker 
      has dedicated his career to the advancement of company goals and the training, 
      mentoring and advancement of employees.</p>
    </div>
  </div>
  
<hr />

  <div class="row">
    <div class="col-xs-4 col-sm-4 col-md-3 col-lg-3 col-xl-2">
      <%= image_tag("final1.gif", :alt=> "Tyler Walker", class: "img-responsive bio") %>
    </div>
    <div class="col-xs-8 col-sm-8 col-md-9 col-lg-9 col-xl-10">
      <h1>Tyler Walker, MS, CSCS, USAW</h1>
      <p class="text-justify">Managing Partner Tyler Walker works with health and technology customers to provide brilliant, turn-key
      solutions to their needs. With over 14 years in fitness and 13 years in web development 
      and graphic design, Tyler has the knowledge and experience to provide you with everything 
      you need and want to create the body or website you want.</p>
      <p class="text-justify">In his 14 years of fitness, Tyler has been a collegiate athlete, powerlifting world 
      record holder, bodybuilder, olympic weightlifter and a collegiate strength and conditioning 
      coach. In his time as a powerlifting, bodybuilding and strength and conditioning coach, 
      Tyler has worked with National Champions, world record holders, Olympic medalists and 
      NFL athletes. With a master's degree and multiple high level certifications, Tyler has the
      education to go along with the experience to get your body performing at its highest levels 
      or looking its absolute best.</p>
      <p class="text-justify">With 13 years of development experience, Tyler has watched as technology has changed 
      over the years. He has seen languages become more dynamic and responsive than ever. Tyler 
      codes in HTML, CSS, Ruby on Rails, JavaScript and a little bit of PHP. He also has 
      experience working in WordPress to create dynamic websites. With experience in multiple 
      sectors including marketing and aerospace, Tyler can provide you the perspective and website 
      to drive lead creation and conversion.</p>
    </div>
  </div>
  
  <br />
  
  </div>
</div>

saasapp/app/views/pages/aviation.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center">Aviation</h1>
    
    <div class="row">
      <h3>Business Development</h3>
      <p class="text-justify">HAVIT provides assistance in creating/growing a business development plan. 
      Creating a strategic short and long term vision is a critical piece of any 
      successful business. The ability to plan and execute a business strategy is 
      the difference between success and failure.</p>
      
      <h4>Capture Planning</h4>
      <p class="text-justify">HAVIT provides assistance in the development of the capture plan which 
      requires very specific data and analysis for the completion of the proposal 
      and award. The capture process becomes a mix of business development and 
      proposal planning by gathering information related to historical data, past 
      performance, customer requirements, and strategy to win. The capture plan 
      truly drives the start to finish process by incorporating elements of 
      business development, proposal management and program execution.</p>
    
      <h4>Proposal Development and Management</h4>
      <p class="text-justify">Proposal Development and Management requires the incorporation of RFP 
      requirements to the production of the final proposal by orchestrating a 
      well-organized and systematic process/procedure designed to capture all 
      the required elements of the RFP. HAVIT uses elements of the Shipley proposal 
      development method and adapts them to the individual customer needs.   </p>
    </div>
    
    <hr />
      
    <div class="row">
      <h3>Program Management</h3>
      <p class="text-justify">Program Management is truly a blend of multiple elements requiring extensive 
      knowledge of pre-proposal elements. It requires the working expertise of the 
      proposal and program requirements and the ability to establish specific 
      program milestones and financial goals. HAVIT provides Program Management 
      techniques using Program Management Institute (PMI) elements, which lead to 
      successful program metrics.</p>
      <p class="text-justify">The HAVIT team has experience not only in implementing the PMI method of 
      program and project management, but they are also well versed in teaching it 
      as well. HAVIT is a veteran of the PMI principles and brings those years 
      of experience to the table at every encounter.</p>
    </div>
    
    <hr />
    
    <div class="row">
      <h3>Contract Negotiations and Development</h3>
      <p class="text-justify">Contract Negotiations and Development are a cornerstone of the financial 
      success of any program. Negotiating pre-determined profit levels requires 
      the ability to establish a strong level of trust with the customer, understand 
      the program goals and command a working knowledge of the proposal on the table. 
      HAVIT teaches contract negotiation skills and use of techniques focused on 
      the win-win scenarios. HAVIT uses its years of Military/Commercial contract 
      experience to assist in the review of RFI/RFP requirements and the application 
      of applicable FAR/DFAR clauses and can provide employee training the areas of 
      contract requirements review.</p>
    </div>
    
    <hr />
    
    <div class="row">
      <h3>US Government Pricing</h3>
      <p class="text-justify">US Government Pricing is an area of concern for many small companies. 
      The application of USG mandated pricing methodologies used in USG proposals 
      is unique at best. The understanding of these requirements such as use of 
      BOE (basis of estimate) price justifications are all elements covered by the 
      HAVIT group.</p>
    </div>
    
    <br />
    
    <div class="row">
      <div class="well">
        <h1 class="text-center">Interested in a Consultation?</h1>
        <button type="button" class="btn btn-default btn-lg btn-block">
          <%= link_to "Contact Us Now", new_contact_path %>
        </button>
      </div>
    </div>
  </div>
</div>

saasapp/app/views/pages/careers.html.erb
<div class="container expand">
  <div class="row">
    <h1 class="text-center">Careers</h1>
    
    <div class="col-xs-8 col-sm-8 col-md-6 col-lg-6 col-xl-6 col-xs-offset-2 col-sm-offset-2 col-md-offset-3 col-lg-offset-3 col-xl-offset-3">
      <h2>Current Openings</h2>
      <h4 class="text-justify">HAVIT Consulting is always on the look out for great talent. At the current moment, 
      we do not have any needs, but send us your resume and find us on LinkedIn. We would love 
      to connect with you.</h4>
    </div>
  </div>
</div>

saasapp/app/views/pages/health.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center">Coaching</h1>
    <blockquote><p>Strength and growth only occurs with continued effort and struggle.</p>
    <footer>Napoleon Hill</footer></blockquote>
    <h3>Training Programs</h3>
    <p class="text-justify">HAVIT coaching believes in a scientifically backed method of getting the 
    most out of the human body. We develop custom training programs that help you 
    to achieve what you want and create the body you wish to earn. No two programs 
    are the same and every client receives one-on-one coaching to ensure they are 
    receiving the best program for their goals. Our coach has a Master's degree 
    in Coaching as well as several years of professional experience working with 
    National Champions, Olympic Athletes (multiple sports), professional NFL players 
    and Division 1 athletes across all disciplines. We understand that no two athletes 
    are the same and we work with you to create the result that you want.</p>
    <h4>Programs Offered in:</h4>
    <ul>
      <li>Powerlifting</li>
      <li>Bodybuilding</li>
      <li>Athletic Performance</li>
      <li>Strongman</li>
    </ul>
  </div>
  
  <hr />
    
  <div class="row">
    <h3>Nutrition Programs</h3>
    <p class="text-justify">HAVIT Coaching espouses a flexible dieting methodology which leads to not 
    only to results on stage and on the platform, but also, to an improved relationship 
    with and understanding of the impact food on performance. We believe no food 
    is inherently "bad". Instead, we view food as a fuel and as a short term investment 
    in your long term performance. We simplify our nutrition programs to make the 
    transition to health as easy as possible. </p>
  </div>
  
  <hr />
  
  <div class="row">
    <h3>Contest Prep</h3>
    <p class="text-justify">Contest prep is a massive undertaking for even the most experienced professional. 
    HAVIT Coaching provides you with the objective eye and constant overwatch you need 
    to bring your best package to stage yet. We provide training and nutrition that 
    produces expansive growth and helps you to keep the most muscle possible as you 
    cut down to stage weight.</p>
    <p class="text-justify">With multiple preps under our belt and a vast level of experience to go along 
    with our education, we provide a superior level of personalization and expertise 
    to our clients. From outright amateurs to experienced veterans, we are prepared 
    to help you reach your best physique ever.</p>
  </div>
  
  <br />
  
  <div class="row">
    <div class="well">
      <h1 class="text-center">Interested in a Consultation?</h1>
      <button type="button" class="btn btn-default btn-lg btn-block">
        <%= link_to "Contact Us Now", new_contact_path %>
      </button>
    </div>
  </div>
</div>

saasapp/app/views/pages/home.html.erb
<div class="container-fluid">
  <div class="row home-callout">
    <div class="container">
      <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <div class="hovereffect">
          <%= image_tag("dumbbells.jpg", :alt=> "Health", class: "img-responsive") %>
          <div class="overlay">
            <ul class="info text-center">
              <li><h2><%= link_to "Health", health_path %></h2></li>
              <li>Training Programs</li>
              <li>Nutrition Programs</li>
              <li>Contest Prep</li>
              <li><br /></li>
            </ul>
          </div>
        </div>
      </div>
      
      <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <div class="hovereffect">
          <%= image_tag("dolphin.png", :alt=> "Aviation", class: "img-responsive") %>
          <div class="overlay">
            <ul class="info text-center">
              <li><h2><%= link_to "Aviation", aviation_path %></h2></li>
              <li>Business Development</li>
              <li>Program Management</li>
              <li>Contract Negotiations and Development</li>
              <li>US Government Pricing</li>
              <li><br /></li>
            </ul>
          </div>
        </div>
      </div>
      
      <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <div class="hovereffect">
          <%= image_tag("technology.jpg", :alt=> "Technology", class: "img-responsive") %>
          <div class="overlay">
            <ul class="info text-center">
              <li><h2><%= link_to "Technology", technology_path %></h2></li>
              <li>Web Development</li>
              <li>Graphic Design</li>
              <li><br /></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<br />

<div class="container services-callout">
  <div class="container">
    <div class="row">
      <div class="well">
        <h1 class="text-center">Interested in a Consultation?</h1>
        <button type="button" class="btn btn-default btn-lg btn-block">
          <%= link_to "Contact Us Now", new_contact_path %>
        </button>
      </div>
    </div>
  </div>
</div>

saasapp/app/views/pages/technology.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center">Technology</h1>
    <h3>Web Development</h3>
    <p class="text-justify">With over 12 years of web development experience, HAVIT Consulting provides
    full-stack web development services to meet the customer's needs. Our developer
    has experience developing in Ruby on Rails, HTML, CSS, Javascript and on the 
    Wordpress platform. We have developed websites for companies in multiple business 
    sectors. We deliver the perfect website or application to meet your business needs. 
    We place a heavy emphasis on communication before and after the development phase 
    in order to ensure the successful creation and development of your vision.</p>
    <p class="text-justify">Our development methodology is one of define, develop 
    and then refine. We emphasize defining clear goals and workflows to ensure a 
    smooth and efficient development phase. When we have transitioned to the development 
    phase, we seek to follow best practices while also providing the most effective 
    website to satisfy our customers. After development and final deploy, we enter the refine 
    phase wherein we work with our customers to ensure maximum SEO and efficiency.</p>
    <p class="text-justify">Examples from our portfolio can be viewed below.</p>
  </div>
  
  <div class="row">
    <ul>
      <li><%= link_to "1218 Global", "http://www.1218global.com", :target => "_blank" %></li>
      <li><%= link_to "Bulldog Rescue Squad", "http://www.bulldogrescuesquad.com", :target => "_blank" %></li>
      <li><%= link_to "Convectus Solutions", "http://www.convectus.com", :target => "_blank" %></li>
    </ul>
  </div>
    
    <hr />
    
  <div class="row">
    <h3>Graphic Design</h3>
    <p class="text-justify">Our developer also happens to be our graphic designer. Currently, he is 
    working in the IT consulting sector to create logos and designs for various 
    companies and organizations. Much like our web design development process, 
    he works to define, design and refine the projects he creates for our customers.</p>
  </div>
  
  <hr />
  
  <div class="row">
    <div class="well">
      <h1 class="text-center">Interested in a Consultation?</h1>
      <button type="button" class="btn btn-default btn-lg btn-block">
        <%= link_to "Contact Us Now", new_contact_path %>
      </button>
    </div>
  </div>
</div>